// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/scheduler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskScheduler_StreamTasks_FullMethodName   = "/scheduler.TaskScheduler/StreamTasks"
	TaskScheduler_StreamResults_FullMethodName = "/scheduler.TaskScheduler/StreamResults"
	TaskScheduler_SubmitTask_FullMethodName    = "/scheduler.TaskScheduler/SubmitTask"
	TaskScheduler_HealthCheck_FullMethodName   = "/scheduler.TaskScheduler/HealthCheck"
)

// TaskSchedulerClient is the client API for TaskScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskScheduler service definition
type TaskSchedulerClient interface {
	// Bidirectional streaming for task distribution
	StreamTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskRequest, TaskResponse], error)
	// Bidirectional streaming for task results
	StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskResult, TaskAck], error)
	// Submit a new task
	SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type taskSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskSchedulerClient(cc grpc.ClientConnInterface) TaskSchedulerClient {
	return &taskSchedulerClient{cc}
}

func (c *taskSchedulerClient) StreamTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskRequest, TaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskScheduler_ServiceDesc.Streams[0], TaskScheduler_StreamTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskRequest, TaskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskScheduler_StreamTasksClient = grpc.BidiStreamingClient[TaskRequest, TaskResponse]

func (c *taskSchedulerClient) StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskResult, TaskAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskScheduler_ServiceDesc.Streams[1], TaskScheduler_StreamResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskResult, TaskAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskScheduler_StreamResultsClient = grpc.BidiStreamingClient[TaskResult, TaskAck]

func (c *taskSchedulerClient) SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTaskResponse)
	err := c.cc.Invoke(ctx, TaskScheduler_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskSchedulerClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TaskScheduler_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskSchedulerServer is the server API for TaskScheduler service.
// All implementations must embed UnimplementedTaskSchedulerServer
// for forward compatibility.
//
// TaskScheduler service definition
type TaskSchedulerServer interface {
	// Bidirectional streaming for task distribution
	StreamTasks(grpc.BidiStreamingServer[TaskRequest, TaskResponse]) error
	// Bidirectional streaming for task results
	StreamResults(grpc.BidiStreamingServer[TaskResult, TaskAck]) error
	// Submit a new task
	SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedTaskSchedulerServer()
}

// UnimplementedTaskSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskSchedulerServer struct{}

func (UnimplementedTaskSchedulerServer) StreamTasks(grpc.BidiStreamingServer[TaskRequest, TaskResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTasks not implemented")
}
func (UnimplementedTaskSchedulerServer) StreamResults(grpc.BidiStreamingServer[TaskResult, TaskAck]) error {
	return status.Error(codes.Unimplemented, "method StreamResults not implemented")
}
func (UnimplementedTaskSchedulerServer) SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedTaskSchedulerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTaskSchedulerServer) mustEmbedUnimplementedTaskSchedulerServer() {}
func (UnimplementedTaskSchedulerServer) testEmbeddedByValue()                       {}

// UnsafeTaskSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskSchedulerServer will
// result in compilation errors.
type UnsafeTaskSchedulerServer interface {
	mustEmbedUnimplementedTaskSchedulerServer()
}

func RegisterTaskSchedulerServer(s grpc.ServiceRegistrar, srv TaskSchedulerServer) {
	// If the following call panics, it indicates UnimplementedTaskSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskScheduler_ServiceDesc, srv)
}

func _TaskScheduler_StreamTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskSchedulerServer).StreamTasks(&grpc.GenericServerStream[TaskRequest, TaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskScheduler_StreamTasksServer = grpc.BidiStreamingServer[TaskRequest, TaskResponse]

func _TaskScheduler_StreamResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskSchedulerServer).StreamResults(&grpc.GenericServerStream[TaskResult, TaskAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskScheduler_StreamResultsServer = grpc.BidiStreamingServer[TaskResult, TaskAck]

func _TaskScheduler_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskSchedulerServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskScheduler_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskSchedulerServer).SubmitTask(ctx, req.(*SubmitTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskScheduler_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskSchedulerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskScheduler_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskSchedulerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskScheduler_ServiceDesc is the grpc.ServiceDesc for TaskScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.TaskScheduler",
	HandlerType: (*TaskSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _TaskScheduler_SubmitTask_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TaskScheduler_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTasks",
			Handler:       _TaskScheduler_StreamTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamResults",
			Handler:       _TaskScheduler_StreamResults_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/scheduler.proto",
}
